version: 2
jobs:
  build:
    branches:
      only:
        - /.*/
    docker:
      - image: circleci/node:10.17
    working_directory: ~/postcss-trash-killer
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm audit
      - run: npm run lint
      - run: npm run test
